<?xml version="1.0"?>
<!--
Software License Agreement (BSD)

\file      husky.urdf.xacro
\authors   Paul Bovbel <pbovbel@clearpathrobotics.com>, Devon Ash <dash@clearpathrobotics.com>
\copyright Copyright (c) 2015, Clearpath Robotics, Inc., All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:
 * Redistributions of source code must retain the a<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- T265 Fisheye:

  gazebo_ros_camera supports only plumb_bob
  D: [-0.007419134024530649, 0.041209351271390915, -0.03811917081475258, 0.006366158835589886, 0.0]

  <distortionK1>-0.007419134024530649</distortionK1>
  <distortionK2>0.041209351271390915</distortionK2>
  <distortionK3>-0.03811917081475258</distortionK3>
  <distortionT1>0.006366158835589886</distortionT1>
  <distortionT2>0.0</distortionT2>

       [fx'  0  cx' Tx]
   P = [ 0  fy' cy' Ty]
       [ 0   0   1   0]

   P : [ 285.5480041503906, 0.0, 416.00531005859375, 0.0,
         0.0, 285.3793029785156, 403.38909912109375, 0.0,
         0.0, 0.0, 1.0, 0.0 ]

  <CxPrime>416.00531005859375</CxPrime>

       [fx  0 cx]
   K = [ 0 fy cy]
       [ 0  0  1]

   K : [ 285.5480041503906, 0.0, 416.00531005859375,
         0.0, 285.3793029785156, 403.38909912109375,
         0.0, 0.0, 1.0]

  <Cx>16.00531005859375</Cx>
  <Cy>403.38909912109375</Cy>

  -->

  <xacro:macro name="T265_fisheye" params="sensor_name reference_frame topic rate">
    <gazebo reference="${reference_frame}">
      <sensor name="camera" type="wideanglecamera">
        <camera>
          <horizontal_fov>6.283</horizontal_fov>
          <image>
            <width>800</width>
            <height>848</height>
          </image>
          <clip>
            <near>0.1</near>
            <far>100</far>
          </clip>
          <lens>
            <type>custom</type>
            <custom_function>
              <c1>1.05</c1>
              <c2>4</c2>
              <f>1.0</f>
              <fun>tan</fun>
            </custom_function>
            <scale_to_hfov>true</scale_to_hfov>
            <cutoff_angle>3.1415</cutoff_angle>
            <env_texture_size>512</env_texture_size>
          </lens>
          <always_on>true</always_on>
          <update_rate>30</update_rate>
        </camera>
        <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>${rate}</updateRate>
          <cameraName>${sensor_name}/${topic}</cameraName>
          <imageTopicName>image_raw</imageTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <frameName>${reference_frame}</frameName>
          <hackBaseline>0.07</hackBaseline>
          <distortionK1>-0.007419134024530649</distortionK1>
          <distortionK2>0.041209351271390915</distortionK2>
          <distortionK3>-0.03811917081475258</distortionK3>
          <distortionT1>0.006366158835589886</distortionT1>
          <distortionT2>0.0</distortionT2>
          <CxPrime>416.00531005859375</CxPrime>
          <Cx>16.00531005859375</Cx>
          <Cy>403.38909912109375</Cy>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>

  <!-- INTEL REALSENSE T265 -->

  <xacro:macro name="realsense_T265" params="sensor_name parent_link rate *origin">

    <joint name="${sensor_name}_odom_frame_joint" type="fixed">
        <parent link="${parent_link}"/>
        <child link="${sensor_name}_odom_frame"/>
        <xacro:insert_block name="origin"/>
    </joint>

    <joint name="${sensor_name}_pose_frame_joint" type="fixed">
        <parent link="${sensor_name}_odom_frame"/>
        <child link="${sensor_name}_pose_frame"/>
        <origin rpy="0 0 0" xyz="0 0 0"/> <!-- check on real hw -->
    </joint>
    <link name="${sensor_name}_odom_frame"/>

    <link name="${sensor_name}_pose_frame">
        <visual>
            <origin rpy="1.57 0 1.57" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://realsense_ros_gazebo/meshes/realsense_t265.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="0.013 0.108 0.024"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.055"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="9.108e-05"
                     ixy="0"
                     ixz="0"
                     iyy="2.51e-06"
                     iyz="0"
                     izz="8.931e-05"/>
        </inertial>
    </link>

    <joint name="${sensor_name}_joint" type="fixed">
        <parent link="${sensor_name}_pose_frame"/>
        <child link="${sensor_name}_link"/>
        <origin rpy="0 0 0" xyz="0 0 0"/> <!-- check on real hw -->
    </joint>
    <link name="${sensor_name}_link"/>

    <joint name="${sensor_name}_fisheye1_joint" type="fixed">
        <parent link="${sensor_name}_link"/>
        <child link="${sensor_name}_fisheye1_frame"/>
        <origin rpy="0 0 0" xyz="0 0.042 0"/>
    </joint>
    <link name="${sensor_name}_fisheye1_frame"/>

    <joint name="${sensor_name}_fisheye1_optical_joint" type="fixed">
        <parent link="${sensor_name}_fisheye1_frame"/>
        <child link="${sensor_name}_fisheye1_optical_frame"/>
        <origin rpy="0 0 0" xyz="0.01 0 0"/>
    </joint>
    <link name="${sensor_name}_fisheye1_optical_frame"/>
    <xacro:T265_fisheye
      sensor_name="${sensor_name}"
      reference_frame="${sensor_name}_fisheye1_optical_frame"
      topic="fisheye1"
      rate="${rate}">
    </xacro:T265_fisheye>

    <joint name="${sensor_name}_fisheye2_joint" type="fixed">
        <parent link="${sensor_name}_link"/>
        <child link="${sensor_name}_fisheye2_frame"/>
        <origin rpy="0 0 0" xyz="0 -0.022 0"/>
    </joint>
    <link name="${sensor_name}_fisheye2_frame"/>

    <joint name="${sensor_name}_fisheye2_optical_joint" type="fixed">
        <parent link="${sensor_name}_fisheye2_frame"/>
        <child link="${sensor_name}_fisheye2_optical_frame"/>
        <origin rpy="0 0 0" xyz="0.01 0 0"/>
    </joint>
    <link name="${sensor_name}_fisheye2_optical_frame"/>
    <xacro:T265_fisheye
      sensor_name="${sensor_name}"
      reference_frame="${sensor_name}_fisheye2_optical_frame"
      topic="fisheye2"
      rate="${rate}">
    </xacro:T265_fisheye>

    <joint name="${sensor_name}_gyro_joint" type="fixed">
        <parent link="${sensor_name}_link"/>
        <child link="${sensor_name}_gyro_frame"/>
        <origin rpy="0 0 0" xyz="0 0 0"/> <!-- check on real hw -->
    </joint>
    <link name="${sensor_name}_gyro_frame"/>

    <gazebo reference="${sensor_name}_gyro_frame">
        <gravity>true</gravity>
        <sensor name="${sensor_name}_imu" type="imu">
            <always_on>true</always_on>
            <update_rate>${rate}</update_rate>
            <visualize>false</visualize>
            <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
                <topicName>${sensor_name}/gyro/sample</topicName>
                <bodyName>${sensor_name}_pose_frame</bodyName>
                <updateRateHZ>${rate}</updateRateHZ>
                <gaussianNoise>0.000001</gaussianNoise>
                <xyzOffset>0 0 0</xyzOffset>
                <rpyOffset>0 0 0</rpyOffset>
                <frameName>${sensor_name}_link</frameName>
            </plugin>
        </sensor>
    </gazebo>

    <joint name="${sensor_name}_accel_joint" type="fixed">
        <parent link="${sensor_name}_link"/>
        <child link="${sensor_name}_accel_frame"/>
        <origin rpy="0 0 0" xyz="0 0 0"/> <!-- check on real hw -->
    </joint>
    <link name="${sensor_name}_accel_frame"/> <!-- dummy -->

    <gazebo> <!-- odometry -->
        <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>${rate}</updateRate>
            <bodyName>${sensor_name}_odom_frame</bodyName>
            <topicName>${sensor_name}/odom/sample</topicName>
            <gaussianNoise>0.001</gaussianNoise>
            <frameName>world</frameName>
            <xyzOffsets>0 0 0</xyzOffsets>
            <rpyOffsets>0 0 0</rpyOffsets>
        </plugin>
    </gazebo>

  </xacro:macro>

</robot>
bove copyright notice, this list of conditions and the
   following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
   following disclaimer in the documentation and/or other materials provided with the distribution.
 * Neither the name of Clearpath Robotics nor the names of its contributors may be used to endorse or promote
   products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WAR-
RANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, IN-
DIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<robot name="husky" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:arg name="laser_enabled" default="false" />
  <xacro:arg name="laser_xyz" default="$(optenv HUSKY_LMS1XX_XYZ 0.2206 0.0 0.00635)" />
  <xacro:arg name="laser_rpy" default="$(optenv HUSKY_LMS1XX_RPY 0.0 0.0 0.0)" />

  <xacro:arg name="kinect_enabled" default="false" />
  <xacro:arg name="kinect_xyz" default="$(optenv HUSKY_KINECT_XYZ 0 0 0)" />
  <xacro:arg name="kinect_rpy" default="$(optenv HUSKY_KINECT_RPY 0 0.18 3.14)" />

  <xacro:arg name="realsense_enabled" default="false" />
  <xacro:arg name="realsense_xyz" default="$(optenv HUSKY_REALSENSE_XYZ 0 0 0)" />
  <xacro:arg name="realsense_rpy" default="$(optenv HUSKY_REALSENSE_RPY 0 0 0)" />
  <xacro:arg name="realsense_mount" default="$(optenv HUSKY_REALSENSE_MOUNT_FRAME sensor_arch_mount_link)" />

  <xacro:property name="husky_front_bumper_extend" value="$(optenv HUSKY_FRONT_BUMPER_EXTEND 0)" />
  <xacro:property name="husky_rear_bumper_extend" value="$(optenv HUSKY_REAR_BUMPER_EXTEND 0)" />

  <xacro:arg name="robot_namespace" default="/" />
  <xacro:arg name="urdf_extras" default="empty.urdf" />

  <!-- Included URDF/XACRO Files -->
  <xacro:include filename="$(find husky_description)/urdf/decorations.urdf.xacro" />
  <xacro:include filename="$(find husky_description)/urdf/wheel.urdf.xacro" />

  <xacro:include filename="$(find husky_description)/urdf/accessories/kinect_camera.urdf.xacro"/>
  <xacro:include filename="$(find husky_description)/urdf/accessories/intel_realsense.urdf.xacro"/>
  <xacro:include filename="$(find husky_description)/urdf/accessories/sick_lms1xx_mount.urdf.xacro"/>
  <xacro:include filename="$(find husky_description)/urdf/accessories/sensor_arch.urdf.xacro"/>

  <xacro:property name="M_PI" value="3.14159"/>

  <!-- Base Size -->
  <xacro:property name="base_x_size" value="0.98740000" />
  <xacro:property name="base_y_size" value="0.57090000" />
  <xacro:property name="base_z_size" value="0.24750000" />

  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="0.5120" />
  <xacro:property name="track" value="0.5708" />
  <xacro:property name="wheel_vertical_offset" value="0.03282" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.1143" />
  <xacro:property name="wheel_radius" value="0.1651" />

  <!-- Base link is the center of the robot's bottom plate -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://husky_description/meshes/base_link.dae" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="${( husky_front_bumper_extend - husky_rear_bumper_extend ) / 2.0} 0 ${base_z_size/4}" rpy="0 0 0" />
      <geometry>
        <box size="${ base_x_size + husky_front_bumper_extend + husky_rear_bumper_extend } ${base_y_size} ${base_z_size/2}"/>
      </geometry>
    </collision>
    <collision>
      <origin xyz="0 0 ${base_z_size*3/4-0.01}" rpy="0 0 0" />
      <geometry>
        <box size="${base_x_size*4/5} ${base_y_size} ${base_z_size/2-0.02}"/>
      </geometry>
    </collision>
  </link>

  <!-- Base footprint is on the ground under the robot -->
  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="base_footprint" />
  </joint>

  <!-- Interial link stores the robot's inertial information -->
  <link name="inertial_link">
    <inertial>
      <mass value="46.034" />
      <origin xyz="-0.00065 -0.085 0.062" />
      <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" />
    </inertial>
  </link>

  <joint name="inertial_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="inertial_link" />
  </joint>

  <!-- IMU Link is the standard mounting position for the UM6 IMU.-->
  <!-- Can be modified with environment variables in /etc/ros/setup.bash -->
  <link name="imu_link"/>
  <joint name="imu_joint" type="fixed">
    <origin xyz="$(optenv HUSKY_IMU_XYZ 0.19 0 0.149)" rpy="$(optenv HUSKY_IMU_RPY 0 -1.5708 3.1416)" />
    <parent link="base_link" />
    <child link="imu_link" />
  </joint>
  <gazebo reference="imu_link">
  </gazebo>

  <!-- Husky wheel macros -->
  <xacro:husky_wheel wheel_prefix="front_left">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:husky_wheel>
  <xacro:husky_wheel wheel_prefix="front_right">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:husky_wheel>
  <xacro:husky_wheel wheel_prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:husky_wheel>
  <xacro:husky_wheel wheel_prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:husky_wheel>

  <xacro:husky_decorate />

  <xacro:if value="$(arg laser_enabled)">

    <sick_lms1xx_mount prefix="base"/>

    <sick_lms1xx frame="base_laser" topic="scan" robot_namespace="$(arg robot_namespace)"/>

    <joint name="laser_mount_joint" type="fixed">
      <origin xyz="$(arg laser_xyz)" rpy="$(arg laser_rpy)" />
      <parent link="top_plate_link" />
      <child link="base_laser_mount" />
    </joint>

  </xacro:if>

  <!-- top sensor arch; include this if we have either the kinect or realsense enabled -->
  <xacro:property name="topbar_needed_kinect" value="$(arg kinect_enabled)" />
  <xacro:property name="topbar_needed_realsense" value="$(arg realsense_enabled)" />
  <xacro:if value="${topbar_needed_kinect or topbar_needed_realsense}">
    <xacro:sensor_arch prefix="" parent="top_plate_link">
      <origin xyz="-0.35 0 0.51" rpy="0 0 -3.14"/>
    </xacro:sensor_arch>
  </xacro:if>

  <!-- add the kinect for xbox 360 to the topbar if needed -->
  <!-- NOTE: this camera is considered depricated -->
  <xacro:if value="$(arg kinect_enabled)">
    <joint name="kinect_frame_joint" type="fixed">
      <origin xyz="$(arg kinect_xyz)" rpy="$(arg kinect_rpy)" />
      <parent link="sensor_arch_mount_link"/>
      <child link="camera_link"/>
    </joint>
    <xacro:kinect_camera prefix="camera" robot_namespace="$(arg robot_namespace)"/>
  </xacro:if>

  <!-- add the intel realsense to the topbar if needed -->
  <xacro:if value="$(arg realsense_enabled)">
    <link name="realsense_mountpoint"/>
    <joint name="realsense_mountpoint_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 -3.14159" />
      <parent link="$(arg realsense_mount)"/>
      <child link="realsense_mountpoint" />
    </joint>
    <xacro:intel_realsense_mount prefix="camera" topic="realsense" parent_link="realsense_mountpoint"/>
  </xacro:if>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
      <legacyModeNS>true</legacyModeNS>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="imu_controller" filename="libhector_gazebo_ros_imu.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
      <updateRate>50.0</updateRate>
      <bodyName>base_link</bodyName>
      <topicName>imu/data</topicName>
      <accelDrift>0.005 0.005 0.005</accelDrift>
      <accelGaussianNoise>0.005 0.005 0.005</accelGaussianNoise>
      <rateDrift>0.005 0.005 0.005 </rateDrift>
      <rateGaussianNoise>0.005 0.005 0.005 </rateGaussianNoise>
      <headingDrift>0.005</headingDrift>
      <headingGaussianNoise>0.005</headingGaussianNoise>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="gps_controller" filename="libhector_gazebo_ros_gps.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
      <updateRate>40</updateRate>
      <bodyName>base_link</bodyName>
      <frameId>base_link</frameId>
      <topicName>navsat/fix</topicName>
      <velocityTopicName>navsat/vel</velocityTopicName>
      <referenceLatitude>49.9</referenceLatitude>
      <referenceLongitude>8.9</referenceLongitude>
      <referenceHeading>0</referenceHeading>
      <referenceAltitude>0</referenceAltitude>
      <drift>0.0001 0.0001 0.0001</drift>
    </plugin>
  </gazebo>

  <!-- Optional custom includes. -->
  <xacro:include filename="$(arg urdf_extras)" />

</robot>

