
global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 10.0
   publish_frequency: 10.0
   width: 40.0
   height: 40.0
   resolution: 0.05
  
   rolling_window: true

   obstacles:
       observation_sources: laser_scan_sensor

       laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /skid_steer_robot/laser/scan, marking: true, clearing: true}

    
   plugins:
   -
     name: footprint
     type: "costmap_2d::StaticLayer"
   -
     name: obstacles    
     type: "costmap_2d::ObstacleLayer"

   -
     name: inflation               
     type: "costmap_2d::InflationLayer"

NavfnROS:
   allow_unknown: false
   default_tolerance: 0.05
   visualize_potential: true # false
   planner_costmap_publish_frequency: 0.2
