local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint

   update_frequency: 10.0
   publish_frequency: 10.0
   width: 6.0
   height: 6.0
   resolution: 0.05
    

   obstacles:
       observation_sources: laser_scan_sensor

       laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /skid_steer_robot/laser/scan, marking: true, clearing: true}


   

   rolling_window: true
   plugins:
   -

      name: footprint
      type: "costmap_2d::StaticLayer"

   -
     name: obstacles    
     type: "costmap_2d::ObstacleLayer"

   -
     name: inflation               
     type: "costmap_2d::InflationLayer"


   
